theme: jekyll-theme-midnight
title: Political Campaign Contribution Networks

description: In my Complex Network Science Class (Math 168, UCLA, Spring 2018), I studied utilized networks created from political campaign contribution data in order to identify and study trends in donation patterns, voting patterns, and election results. 
